# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Example add-on
version: "1.2.5"
slug: example
description: Example add-on
url: "https://github.com/ihuf/addons-example"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - addons:rw
  - all_addon_configs:rw
  - backup:rw
  - homeassistant_config:rw
  - media:rw
  - share:rw
  - ssl:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
full_access: true
advanced: true
privileged:
  - DAC_READ_SEARCH
  - IPC_LOCK
  - NET_ADMIN
  - NET_RAW
  - SYS_ADMIN
  - SYS_MODULE
  - SYS_NICE
  - SYS_PTRACE
  - SYS_RAWIO
  - SYS_RESOURCE
  - SYS_TIME

init: false
host_pid: true
